# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmanagement', '0002_auto_20160903_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_count',
            field=models.IntegerField(default=0),
        ),
    ]
