# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmanagement', '0004_auto_20160919_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_per_piece',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
